language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm # on Trusty only
  - nightly
script: "phpunit --report-useless-tests --strict-coverage --disallow-test-output --colors --configuration tests/phpunit.xml"
before_install: "composer install --dev"
