language: php
php:
  # - '5.5'
  # - '5.6'
  # - '7.0'
  # - '7.1'
  - hhvm # on Trusty only
  # - nightly
before_install: "composer install --dev"
before_script:
  - curl -sSf -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
script: "phpunit --configuration tests/phpunit.xml"
